### PR TITLE
PR for Journal/Tutorial

### PR DESCRIPTION
**Pull request by jeremyrist**

### CODE REVIEW

**Comment by s4dmw** [comment]
Journal is looking good and the turtorial is shaping up nicely! nice work. :+1:

**Comment by ericquayson** [comment]
:+1:  I agree with Meek Mill being removed from the array. Good job.

**Comment by jeffworley** [comment]
Really solid writing mane.  I can completely relate as it pertains to voicing up when unsure of something we are covering in class.  I always have a voice in the back of my head saying _should I understand this right away_ that I wrestle with.  As for the tutorial, I think you have picked a great topic and your justification for teaching it makes perfect sense.  Also glad to see Bronsolinio mentioned in the array.  Great work :+1:

**Comment by rosalsm** [comment]
I like the array of chairs :+1:   very graphic. Have you thought of push as another opposite of pop?

**Comment by jeffworley** [comment]
Still looks good mane.  As a "newbie" reading it, it is easy to follow and understand :+1:

**Pull request merged**
